module.exports = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',
  SWITCH_TITLE: 'SWITCH_TITLE',

  GET_TASKS_LIST: 'GET_TASKS_LIST',
  GET_PENDING_TASKS_LIST: 'GET_PENDING_TASKS_LIST',
  GET_COMPLETED_TASKS_LIST: 'GET_COMPLETED_TASKS_LIST',
  CREATE_TASK: 'CREATE_TASK',
  COMPLETED_TASK: 'COMPLETED_TASK',
  UNDO_TASK: 'UNDO_TASK'
};
